language: node_js
node_js:
  - '0.10'
before_install:
  - 'gem install sass --version "~> 3.2"'
  - 'gem install compass --version "~> 0.12"'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
